-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgzWZJ82lF6ZYkkxuY
hPz0wVGzfVui0cDUqzkHPmRbUnigCgYIKoZIzj0DAQehRANCAAQB3seL/2mpvd6y
p1TgQ4SU2oICNpd4K5rKAQeMeA/eiI63q6+k8jLpM1grPjjXKhpeptfJn0vkFX7y
AJdkmNzJ
-----END PRIVATE KEY-----